### ISSUE TITLE
The last price will incorrectly disappear if current promotion last more than 30 days

### ISSUE THREAD

**Issue by PiotrCzapla** [perfectlyproject/perfectwp-wc-omnibus#1]
When you look for the last price in 30 days you take the current date minus 30 days, so if the promotion last more than 30 days the last price will disappear.

According to the law you should take the start date of the current promotion and then deduct 30 days. It can be done in sql with a window function or a subquery. Both should be quite fast (faster than going back end forth between php and mysql)

**Comment by SlawomirLech95** [comment]
The issue has been fixed in release 1.0.4
